server:
    port: 7070
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://eureka-service:8761/eureka
    instance:
        hostname: eureka-service
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: client-service
                  uri: lb://client-service
                  predicates:
                    - Path=/client/**
                    