server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: docker
          uri: https://github.com/RECAVERO/microservicio_springboot/
          search-paths: config-data
  application:
    name: config-service
